name: React.js CI/CD

on:
  # push:
  #   branches:
  #     - master
  # pull_request:
  #   branches:
  #     - master

jobs:
  build: 
    name: Build React App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Install Dependencies with Yarn
        run: yarn install

      - name: Build React Application with Yarn
        run: yarn build # This creates the 'build' folder
